apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: pwa-hello
  namespace: default
  annotations:
    openchoreo.dev/display-name: Hello PWA
    openchoreo.dev/description: A simple installable PWA served by nginx
spec:
  owner:
    projectName: default
  componentType:
    kind: ClusterComponentType
    name: deployment/web-application
  autoBuild: false
  autoDeploy: true
  workflow:
    kind: ClusterWorkflow
    name: docker-gitops-release
    parameters:
      componentName: pwa-hello
      projectName: default
      repository:
        url: https://github.com/rashadism/pwa-hello
        revision:
          branch: main
          commit: e73703bb9acae36def0ee42d7b6a8767f77c219e
        appPath: /
      docker:
        context: /
        filePath: /Dockerfile
      workloadDescriptorPath: workload.yaml
